version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: statsplainer_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      
  backend:
    build: ./backend
    container_name: statsplainer_backend
    ports:
      - "5050:5000"
    environment:
      - FLASK_DEBUG=1
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./persistent_data/pdfs:/app/pdf_uploads
      - ./persistent_data/images:/app/img_uploads
      - ./persistent_data/database:/app/database
      - ./backend/prompts:/app/prompts

